{% set version = "1.3.1" %}

package:
  name: pytest-console-scripts
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-console-scripts/pytest-console-scripts-{{ version }}.tar.gz
  sha256: 5c6c3daae9cf9fbed0e655072128938600193dc002a5cf1b187248644ba02857

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - mock >=2.0.0
    - pytest >=4.0.0
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - pytest_console_scripts
  commands:
    - pip check
    - pytest -vv --cov pytest_console_scripts -k "not test_env[subprocess]"
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/kvas-it/pytest-console-scripts
  summary: Pytest plugin for testing console scripts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - holgern
    - bollwyvl
