{% set name = "pytest-console-scripts" %}
{% set version = "1.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: caeaaaf57f3a99e4482127e8a18467a1cfd49c92f4b37e5578d0bc40bf1b3394

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools-scm
  run:
    - mock >=2.0.0
    - pytest >=4.0.0
    - python >=3.5

test:
  source_files:
    - tests
  imports:
    - pytest_console_scripts
  commands:
    - pip check
    - pytest -vv --cov pytest_console_scripts -k "not test_env[subprocess]"
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/kvas-it/pytest-console-scripts
  summary: Pytest plugin for testing console scripts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - holgern
    - bollwyvl
