{% set name = "pytest-console-scripts" %}
{% set version = "1.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a2138d7d567bc581fe081b6a5975849a2a36b3925cb0f066d2380103e13741c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools-scm >6
  run:
    - mock >=2.0.0
    - pytest >=4.0.0
    - python >=3.5

test:
  source_files:
    - tests
  imports:
    - pytest_console_scripts
  commands:
    - pip check
    - pytest -vv --cov pytest_console_scripts -k "not test_env[subprocess]"
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/kvas-it/pytest-console-scripts
  summary: Pytest plugin for testing console scripts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - holgern
    - bollwyvl
