travis:
  secure:
    BINSTAR_TOKEN: JDBYtsA4ES8GEhpwg+ja9/s76Cw4pE3BX1J4dJ6pJpPXiBMMc7WiPyZvzZtdZZnc3uCWiBVcL4EcYtlvS5qjXGNj5XlVGgk3PjDo0QPQfjpgszUWZTdNjCkOMxI1BjlBwe8d2bIsyMlxQHGsrfGNVCVMJ3Wr5QU2v7T9HxeIRt+rNLOXVWwmCHzfoOS4gb6dE9yV+RHW3SJOkWV/E5UEqacjK1JjwOypnIxvO4mbwDa/SJWfMmtqV6iKbVHSqB0vAFOpFKEqtJpmhacJda6bhtpA3ZWHUigqMefgI6wF5Ieg3Pm/5o0JKXXFtLtbInJhaxCJgkNbeBxcYSJ1CCUE/7sCpQdzDk4Rtiey5UNLPmH5wLMm9i5UAoEIpWebBnSsN192DZXVjabOA/lPmVaMwug8LB5aOocnbF3cgF+UMwi06BWNVwto4ZtDRdbdsLjQnWeez9b9kB1XlQIi7chvB30T2AhCmINYYUY1ed2n15VqL8Z6Ym1/xwegYn++ryvoON9jKPX1YFWSSvp400h/qP5abf8LfsUV/PPSpzjGgYewaFQrLInZBZiOsye1wOHSw5UHWzXY8vhHWGQgRV3PWOnhPWmUgraAL2Ln9Yd7v0K7EmS4k3LcZ2MsNWje/amuw1T3OnIAnDUcfkgT5NLN64SCvk7/2hFCod5o3tbkzAM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
