travis:
  secure:
    BINSTAR_TOKEN: RxhvVSW5B9nXCA5bUikY9Jwczu9eLusqjJZrs60FTbJNqxbRTv4WkBElKyRTGE8CmxrgbsaiI7rilCAlDjd5uubAHUy+XWC3vBfwPKXOhWRb7xk5A2lajZyIi/XNoxh62B85yRJR7u/t1ohQuzcYNV125B9t0+UDtMvD9TXNSb8ebqHBZbVwZG290WRHadSmu/O6lhV/ZX/VSxg39Uu6wSzwvBxWqxr9P4M3+yLgHzVKOVRrg/jdJRPBGlx/ZQyHZNjzBd7iUTwQ2MGRzloudN7RIF20PK339wHI4RChe6CYMS0K8/SdAD8We77DI4rYFrJ+1L7FRg6Rc1EMaYG/YUOEE4x1elfB5wbCEqL7C4ZpPa5UntDXRd0qwawZPne/uy3dqSJGwl4fqvlsYkLoC5u/K6aCM77Rhwk2csCmFDkSYRE1JcxcXkiiPOq1hV8IjjLXDKV81Ps+s2oVQmHTwFyIjBqn3uoZJ6d4/C69hAW5rDlRBhY+X7SOV0zjJG5t9RS7vtbUrhigRONF6pDOymjXxh8Y47OwvKb1YEQ/zeWy+dOV7iV2oFkUtuvi2ZvTrMEjCk3w11DpTjYVGPFcHzTEQnh/VJL0H87olGkzUk1umkf1DT8xINRh1LxWaVdyAQT2smj2QYgYXZ5CZKahJVgcPBx9nG8bBOv1YT7s4X8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
