travis:
  secure:
    BINSTAR_TOKEN: K3bymgqkVgHSg37ZqVmjU6eMudtXfKujnpulxTaCOhEn7y3nvH5gLxmEf1Ve1cAfbhtiqmJO8POCs9LRcyy3U2peTbMq3d3AYHcaLSHMOv144LMgytHGfI0pZi9Dt1D4xo+X5qm7K3lcgr8tPSNi7UxU2AsnEFCprkZKN2kZY5h6uqEo29PG5TsgUKfog7aYVm8pvZ8yTzOIjFnqztet0e8j3YgzkQ70c8HUDZOGZA4ik4k89oRjw+mm312MzyEAPFuL5Mdw4Hq78xV3l27L+qiuyVRcA6bNwPCP13TyU9GcZcSsfEx40/djAYGHsZkJQ3HT2LHxsmUfP1EEtv9DpurBqVicA/HPEiRVFKoHtjWwAlGwfKMDW31H4BBVf+aWMIoZD6FocibA/enDLPGHYAPN94ZF5mXW5UQk7jiEPeS+vSeXaTxsbUedxxbPSbdk73m0Quwn/PLEgHeYPwTdoIRXh0w4P2/RAxeXLiips0SD1INxvQkSFCDeGznBwmBowg5Ral7OMBZCD8wCOj228jvqZu2U1YdfA1yphnFhgJw+br3ZxaAGW/EJm8BoW9yQ6QgVOHHFUtUTZQpgGBTA8/ilZzbGF5hB79Qnvoe0mvFOwH9ES/HNMIHljXlaPEkn8cz8FSZG7ZEkuyjCywGI1upmH2hw4EHl8f4th4CDcJg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
